### ISSUE TITLE
Image Search/Select Target/Position box triggering too soon: causing Java exception

### ISSUE THREAD

**Issue by hickst** [Caltech-IPAC/firefly#908]
Using ipac/firefly:rc-2019.3

In the `Images` dropdown, `3. Select Target` area, the `Name or Position` input text box is triggering events too quickly, causing a NED/Simbad lookup before the user has entirely entered the Position coordinates. In the example exception, I was entering `53.16 -27.78` but the NED lookup triggered before I could finish and only `53` was searched in NED. This caused a Java exception as follows:
```
url: https://ned.ipac.caltech.edu:443/cgi-bin/nph-objsearch?extend=no&out_csys=Equatorial&out_equinox=J2000.0&obj_sort=RA+or+Longitude&of=xml_main&zv_breaker=30000.0&list_limit=1&img_stamp=NO&objname=53
java.lang.Exception: Could not resolve 53 using nedthensimbad
	at edu.caltech.ipac.firefly.server.rpc.ResolveServerCommands$ResolveName.doCommand(ResolveServerCommands.java:43)
	at edu.caltech.ipac.firefly.server.ServCommand.processRequest(ServCommand.java:22)
	at edu.caltech.ipac.firefly.server.servlets.CommandService.processRequest(CommandService.java:69)
	at edu.caltech.ipac.firefly.server.servlets.BaseHttpServlet.doService(BaseHttpServlet.java:97)
	at edu.caltech.ipac.firefly.server.servlets.BaseHttpServlet.doGet(BaseHttpServlet.java:83)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.sf.ehcache.constructs.web.filter.GzipFilter.doFilter(GzipFilter.java:95)
	at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at edu.caltech.ipac.firefly.server.filters.CommonFilter.doFilter(CommonFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by robyww** [comment]
The code is working correctly, just logging wrong.  We do aggressive look up as the user is typing. However, it should not be logging as it does.  The message should go into the internal firefly.log file internal to the docker container. 

It appears as something bad but is is not.  However, I will create a ticket to log the message properly.

**Comment by hickst** [comment]
Hi Trey,

Sorry for the confusion then....as the `firefly.log` within the Docker image is where I found the exception reported above.

It does make me wonder though: if you are expecting the exception, why doesn't the code catch it and ignore it, removing the work of logging an entire stack trace to the log file?

**Comment by robyww** [comment]
It should. The code should just log a 1 line message with a success or fail but not exception. 

https://jira.ipac.caltech.edu/browse/FIREFLY-434

**Comment by hickst** [comment]
Got it...thanks.

**Comment by robyww** [comment]
fixed in PR: https://github.com/Caltech-IPAC/firefly/pull/909
